### ISSUE TITLE
Mesh Objects do not have Transforms

### ISSUE THREAD

**Issue by JulianKnodt** [lo48576/fbxcel-dom#22]
Each mesh/geometry should have a set of transforms associated with it, but I am unsure where these attributes are available within  the provided nodes. It would be useful to expose the transforms where they are available, altho I realize it's not immediately clear where they come from. I suspect they're on the attributes of mesh nodes, but converting them into matrices would be convenient.

I am well aware how much of a pain it is to work with FBX, I've been poking at the Assimp Converter for a while, so thanks for your work. If there is anything I can do to contribute please let me know 🙇

**Comment by lo48576** [comment]
`Model (Mesh)` objects should have a `Properties70` node and it may (or may not) have `P` nodes with TRS (with the names `Lcl Translation`, `Lcl Rotation`, and `Lcl Scaling`).
These properties can be retrieved by:

1. assume the variable `mesh` as [`ObjectHandle`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/struct.ObjectHandle.html) type or types that can be converted to it (such as [`MeshHandle`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/model/struct.MeshHandle.html)).
2. Call [`ObjectHandle::properties_by_native_typename`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/struct.ObjectHandle.html#method.properties_by_native_typename) and [`ObjectProperties::get_property`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/struct.ObjectProperties.html#method.get_property) on `mesh` to get a property handle to the metadata. `let t: Option<PropertyHandle<'_>> = mesh.properties_by_native_typename("Lcl Translation").get_property("Lcl Translation");` for example.
3. If the property handle is available, parse the value using [`PropertyHandle::load_value`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/struct.PropertyHandle.html#method.load_value). Use the correct loader for the type of the value. For example, [`MintLoader<Vector3<f64>>`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/trait.LoadProperty.html#impl-LoadProperty%3C'_%3E-for-MintLoader%3CVector3%3Cf64%3E%3E) or [`F64Arr3Loader`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/trait.LoadProperty.html#impl-LoadProperty%3C'_%3E-for-F64Arr3Loader) for `Lcl Translation`.
    + See <https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/trait.LoadProperty.html#implementors> for the list of loaders (or you can write custom one and implement `LoadProperty` trait if the library does not provide things you need).

The first attribute of a `P` node is the proprety name, the next property is the native typename, the next is the label (maybe not so useful), the next is flags (maybe not so useful).
For exmaple, in the `P` node below, the property name is `RotationOffset`, the native typename is `Vector3D`, the label is `Vector`, and the value is `[0.0, 0.0, 0.0]` (as `[f64; 3]`).

![2024-12-14-174021+0900](https://github.com/user-attachments/assets/86db3991-1b70-464d-ba2a-cb388202b05a)

It's not fun but reverse-engineering is possible, and the library (in the current state) provides access to the data using such (relatively) low-level detail in case the library does not have knowledge about something you need.

**Comment by lo48576** [comment]
`Model (Mesh)` objects should have a `Properties70` node and it may (or may not) have `P` nodes with TRS (with the names `Lcl Translation`, `Lcl Rotation`, and `Lcl Scaling`).
These properties can be retrieved by:

1. assume the variable `mesh` as [`ObjectHandle`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/struct.ObjectHandle.html) type or types that can be converted to it (such as [`MeshHandle`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/model/struct.MeshHandle.html)).
2. Call [`ObjectHandle::properties_by_native_typename`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/struct.ObjectHandle.html#method.properties_by_native_typename) and [`ObjectProperties::get_property`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/struct.ObjectProperties.html#method.get_property) on `mesh` to get a property handle to the metadata. `let t: Option<PropertyHandle<'_>> = mesh.properties_by_native_typename("FbxNode").get_property("Lcl Translation");` for example.
3. If the property handle is available, parse the value using [`PropertyHandle::load_value`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/struct.PropertyHandle.html#method.load_value). Use the correct loader for the type of the value. For example, [`MintLoader<Vector3<f64>>`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/trait.LoadProperty.html#impl-LoadProperty%3C'_%3E-for-MintLoader%3CVector3%3Cf64%3E%3E) or [`F64Arr3Loader`](https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/trait.LoadProperty.html#impl-LoadProperty%3C'_%3E-for-F64Arr3Loader) for `Lcl Translation`.
    + See <https://docs.rs/fbxcel-dom/0.0.10/fbxcel_dom/v7400/object/property/trait.LoadProperty.html#implementors> for the list of loaders (or you can write custom one and implement `LoadProperty` trait if the library does not provide things you need).

The first attribute of a `P` node is the proprety name, the next attribute is the property typename on FBX SDK, the next is the label (maybe not so useful), the next is flags (maybe not so useful).
For exmaple, in the `P` node below, the property name is `RotationOffset`, the property typename is `Vector3D`, the label is `Vector`, and the value is `[0.0, 0.0, 0.0]` (as `[f64; 3]`).

![2024-12-14-174021+0900](https://github.com/user-attachments/assets/86db3991-1b70-464d-ba2a-cb388202b05a)

It's not fun but reverse-engineering is possible, and the library (in the current state) provides access to the data using such (relatively) low-level detail in case the library does not have knowledge about something you need.

**Comment by lo48576** [comment]
The list of "native typename"s for objects I know:

| object | native typename |
|:--|:--|
| `AnimationCurveNode` | `FbxAnimCurveNode` |
| `AnimationLayer` | `FbxAnimLayer` |
| `AnimationStack` | `FbxAnimStack` |
| `CollectionExclusive` | `FbxDisplayLayer` |
| `Geometry` | `FbxMesh` |
| `Material` | `FbxSurfaceLambert` |
| `Material` | `FbxSurfacePhong` |
| `Model` | `FbxNode` |
| `NodeAttribute` | `FbxCamera` |
| `NodeAttribute` | `FbxNull` |
| `Texture` | `FbxFileTexture` |
| `Video` | `FbxVideo` |

You should choose the appropriate native typename for an object, based on the class and subclass.

And here is the incomplete list of possibly useful properties for `Model (Mesh)` nodes (whose "native typename" is `FbxNode`):

| property name | property typename (on FBX SDK) | loadable value type |
|:--|:--|:--|
| `QuaternionInterpolate` | `enum` | `i32` |
| `RotationOffset` | `Vector3D` | `[f64; 3]` |
| `RotationPivot` | `Vector3D` | `[f64; 3]` |
| `ScalingOffset` | `Vector3D` | `[f64; 3]` |
| `ScalingPivot` | `Vector3D` | `[f64; 3]` |
| `TranslationActive` | `bool` | `i32` |
| `TranslationMin` | `Vector3D` | `[f64; 3]` |
| `TranslationMax` | `Vector3D` | `[f64; 3]` |
| `TranslationMinX` | `bool` | `i32` |
| `TranslationMinY` | `bool` | `i32` |
| `TranslationMinZ` | `bool` | `i32` |
| `TranslationMaxX` | `bool` | `i32` |
| `TranslationMaxY` | `bool` | `i32` |
| `TranslationMaxZ` | `bool` | `i32` |
| `RotationOrder` | `enum` | `i32` |
| `RotationSpaceForLimitOnly` | `bool` | `i32` |
| `RotationStiffnessX` | `double` | `f64` |
| `RotationStiffnessY` | `double` | `f64` |
| `RotationStiffnessZ` | `double` | `f64` |
| `AxisLen` | `double` | `f64` |
| `PreRotation` | `Vector3D` | `[f64; 3]` |
| `PostRotation` | `Vector3D` | `[f64; 3]` |
| `RotationActive` | `bool` | `i32` |
| `RotationMin` | `Vector3D` | `[f64; 3]` |
| `RotationMax` | `Vector3D` | `[f64; 3]` |
| `RotationMinX` | `bool` | `i32` |
| `RotationMinY` | `bool` | `i32` |
| `RotationMinZ` | `bool` | `i32` |
| `RotationMaxX` | `bool` | `i32` |
| `RotationMaxY` | `bool` | `i32` |
| `RotationMaxZ` | `bool` | `i32` |
| `InheritType` | `enum` | `i32` |
| `ScalingActive` | `bool` | `i32` |
| `ScalingMin` | `Vector3D` | `[f64; 3]` |
| `ScalingMax` | `Vector3D` | `[f64; 3]` |
| `ScalingMinX` | `bool` | `i32` |
| `ScalingMinY` | `bool` | `i32` |
| `ScalingMinZ` | `bool` | `i32` |
| `ScalingMaxX` | `bool` | `i32` |
| `ScalingMaxY` | `bool` | `i32` |
| `ScalingMaxZ` | `bool` | `i32` |
| `GeometricTranslation` | `Vector3D` | `[f64; 3]` |
| `GeometricRotation` | `Vector3D` | `[f64; 3]` |
| `GeometricScaling` | `Vector3D` | `[f64; 3]` |
| `MinDampRangeX` | `double` | `f64` |
| `MinDampRangeY` | `double` | `f64` |
| `MinDampRangeZ` | `double` | `f64` |
| `MaxDampRangeX` | `double` | `f64` |
| `MaxDampRangeY` | `double` | `f64` |
| `MaxDampRangeZ` | `double` | `f64` |
| `MinDampStrengthX` | `double` | `f64` |
| `MinDampStrengthY` | `double` | `f64` |
| `MinDampStrengthZ` | `double` | `f64` |
| `MaxDampStrengthX` | `double` | `f64` |
| `MaxDampStrengthY` | `double` | `f64` |
| `MaxDampStrengthZ` | `double` | `f64` |
| `PreferedAngleX` (not "preferred"!) | `double` | `f64` |
| `PreferedAngleY` (not "preferred"!) | `double` | `f64` |
| `PreferedAngleZ` (not "preferred"!) | `double` | `f64` |
| `LookAtProperty` | `object` | (empty) |
| `UpVectorProperty` | `object` | (empty) |
| `Show` | `bool` | `i32` |
| `NegativePercentShapeSupport` | `bool` | `i32` |
| `DefaultAttributeIndex` | `int` | `i32` |
| `Freeze` | `bool` | `i32` |
| `LODBox` | `bool` | `i32` |
| `Lcl Translation` | `Lcl Translation` | `[f64; 3]` |
| `Lcl Rotation` | `Lcl Rotation` | `[f64; 3]` |
| `Lcl Scaling` | `Lcl Scaling` | `[f64; 3]` |
| `Visibility Inheritance` | `Visibility Inheritance` | `i32` |

You can read FBX SDK references to see what the value actually means.
For example, see <https://help.autodesk.com/cloudhelp/2017/ENU/FBX-Developer-Help/cpp_ref/class_fbx_node.html#a37b5b752bb6a84cdbf8eb8b1ccf9096b> and <https://help.autodesk.com/cloudhelp/2017/ENU/FBX-Developer-Help/cpp_ref/fbxmath_8h.html#a9c7a0dfb52c83256d4a92c5c6d1be72a> for `QuaternionInterpolate` enum.

**Comment by lo48576** [comment]
And to add one more thing: matrices and weights related to movement might be stored in `Deformer` objects and `SubDeformer` objects, but I have almost no knowledge about them...
Download and see <https://github.com/lo48576/fbx_objects_depviz/blob/a3045e94db379a573d34d439ea74f36d08499bb2/examples/all.dot.svg> to find the related object types.
(`all.dot.svg` is large, so open directly in a browser and use the zoom and scroll.)

**Comment by JulianKnodt** [comment]
I think having to know the structure of the FBX to be able to read fields makes it a bit difficult to use this downstream. Since the FBX format is a complete mess, it's pretty difficult to abstract over it, but I think for what I'm looking for I want to get an abstract mesh representation rather than have to deal with the file format's intricacies.
